language: node_js
node_js:
- 10
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_script:
- npm i firebase-tools -g
- npm i @cloudflare/wrangler -g
script:
- npm install
- npm run build
- firebase deploy --only hosting --token $FIREBASE_TOKEN
- cd worker
- wrangler build
- wrangler publish
env:
  global:
  - secure: ekCVnL37s0KdusrqpGeYcQwQc1kW2Fg87+NXnrKOLczg/U5G3nB7SrOdVFDemPMxkKkyaoeu/zY4MTIlmF4+i/puuIjQtEBpJEIcGYxfFSlWq9NXv9gkLBOfrlQlR/WKTzb+XnnOPqBYYLNDibGSdzoPGwp65bWj/kvNyuwX1JyKXVki6yCvfw87ky48LJ6MM+USo3UlPO93KH0EILPpB+hOhgvbwvNqLfZJKZxRgOkcpYy7IE37hLoCNx0dhD9ZxeRQ1N9Q9BIXPC+BvtYyvo5j41lB1i5nuS6YdD9BteNuQslDe9glXYh5Yz03AvUx+KhOJk4tJb8D3bonw565B7i7n11LNGFct60WYlQ/tPle4ymT8b1yfok9Tjuh19XyVVbdqFqQzrfY7knn/6JhrME8YnSUtJtgztMBiNVcCeqWlanXBoquDQlcpvz/n37C3OR+rLVIr6TB8K8qVPJzAoWHcRFJh1phnF55R2o7al6hT86U0a7uNOWYxsOPkft9h/RrwlYpZNo+o2WF9YHCGkcY1Cce63jVbJ7KNcFWFtXKIx8lNh3hDFOO9sMfWINPQXbm1YolMcORz8NVenwYlbFZC/FDcHKZPI8+OrPHDcCrfCq7ndHTM2Or3j3p6cQmIjZqmFvomJKeHHxN12+RoHk6BNvQbfhW9HPjNWbDqu4=
  - secure: nPFmjOmj+iX4TUfueZsgTdhNyr5hIVxWQ3fM4vdzw7+bp0kaVXtFJxAXIWU7YT6vPJG5GCE2uxSyUOha3eWDY2/2u/itqoGozw9vvsw7e2n+wPUMz+b9qZ+XP8EAUBApimbFKSCM4Z1ZRuNPWN7OfuoD1gbOXsuNp+6g0x5ia9sOlzvpLThR2Cd9Uu4aGixyosJO3YmVuBMvgXNSDRXuuim0jDc4/zMAMuQa9npa3FbEjMTi4JvIhDNqyLEGC9zlt7o/3doUiLuGlo+SAddfzM1BZcXJh/n6v0wwdiQQbG6BxRZzAhOpjfk9E+6xeA7f50bSHpM4e2lTeiB1kbj7086DNvBJW0tYpamarvp+owZDCOUygPEbkjrXdPNlhmE0EA74cln9yxAi/wbVXn8JPlFHQ7t2YPvDUL1O/dRt/hoUnF5+m0x211zSlVY+xGdNkmORYLTPNM28zd6PqWQosTz8qCgHH14TZ7dfSMoJKmeETFMVN4ZkWdwSZpIBjGPgbhMvcnAlqRUaT4vBzS5gCfZqFLqbTSDQ+EnOCE3PuPXRym9/QuAiiNS2QvKUvspgdK1WOJvR/BGHKJ0TLHCNR487pMGawnG5ck0NkwNuKvR7d3zrT6N8VJ8nEk3kBfQ7qO9EVjThrjjEvRSdk6IIvMMFOPahowun1fNGMoEQH/I=
  - secure: UmxFxi6XKzmuTx8BdRBSdFLhWv5gE4to0LZos6DgKz2Lg0XCztZyNKcvGQrWs0WVUmX4ImhsESDlEn5JQiVXlelevoanW+L0+2nnLhUkrfk5SeAiyKdhood/df/SeOlAU2uvoM43hqC5PSj740lt9JVQacc6uZgvYk4BQNZWnjSeJfO6k+AXmevVOSMxtHOwo7GqjsdTTciUpnGeTxrlIiPQpJiMswlXwjX0GXvlMsnNFyxyqQbUffC5NKW3dR8howsckz9hXTIHGXe6MGVJjsBkBJWwrDRSO4YOtkuuxAQsdBhjTNCBpHPRt/k+Nw/hTOLLPjR8sQS4AaII6GlIT4NBfgl2BsU0q5agzV8rPPUq8eJObkxcxc/2sWmmFqi2ZN6wct/bMyXxAOY4c3wTU1H5e4H+UC4vA9qUo0h/eRcO5VnUw5niji0LwJWKJa3dBooofV+OCHYT6YLsx6orUCnZndlJZMynbo7jBfy6/CmwREOgdXvQmQMvIUMqT67FbPbfN4XveBHnTForwAADStx0oPYuLn/A4vxc6QLfKVHs3mc/w56NNUf0rt75RTmt5O6DqpUItpgKAuEFOT8JWjvLSwhYh3JCZul5Zl5iKpQ9/bOl35vV2Q9kiEKYaZt7P7kZVgeWxEd+2zIj1jxOpRUszPfOpH0YxP3vCDxAq9E=
